version: '3.8' # Specify the compose file version

services:
  portfolio-app: # Name of the service
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: constant-suchet-portfolio # Optional: A specific name for the container
    ports:
      - "7000:7000" # Map port 3000 on the host to port 3000 in the container
    restart: unless-stopped # Restart policy
    environment:
      # You can add or override environment variables here if needed
      # Example:
      # NUXT_PUBLIC_API_URL: https://api.example.com
      NODE_ENV: production 