/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tuuttipingu (https://sketchfab.com/Tuuttipingu)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/rk-62-m2-53120de9648d4828915927ed35abadf5
Title: RK-62 M2
*/

import React, { useRef } from 'react'
import { RandomizedLight,Float, useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

const Model1 = (props) => {
  const modelRef = useRef();
  const { nodes, materials } = useGLTF('/models/rk.glb')

 // useGSAP( () => {
   // gsap.to(modelRef.current.position, {
     // y: modelRef.current.position.y + 0.5,
      //duration: 1,
      //yoyo: true,
      //repeat: -1,
    //});
  //});

  return (
    <Float dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} {...props}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rk62m_0.geometry}
          material={materials.frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rk62m_1.geometry}
          material={materials.grip}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rk62m_2.geometry}
          material={materials.rails}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rk62m_3.geometry}
          material={materials.stock}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/rk.glb')

export default Model1